# Generated by Django 5.2.3 on 2025-06-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('available_spots', models.IntegerField()),
                ('average_rating', models.FloatField(default=0.0)),
            ],
        ),
    ]
