# Generated by Django 5.2.3 on 2025-07-21 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('opening_hour', models.TimeField()),
                ('closing_hour', models.TimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='garage_images/')),
                ('price_per_hour', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('reservation_grace_period', models.PositiveIntegerField(default=15, help_text='مدة الحجز المؤقت بالدقائق قبل إلغائه تلقائيًا')),
                ('block_duration_hours', models.PositiveIntegerField(default=3, help_text='عدد ساعات الحظر عند الإلغاء المتأخر')),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'garage_owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='owned_garages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GarageReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='garage.garage')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved')], default='available', max_length=10)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='garage.garage')),
            ],
        ),
    ]
