# Generated by Django 5.2.1 on 2025-06-28 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garage',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied')], default='available', max_length=10)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='garage.garage')),
            ],
        ),
    ]
